name: auto deploy release

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment.
        required: true
        default: ftbtest
      branch:
        description: Branch.
        required: true
        default: env/ftbtest


jobs:
 create-new-release:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout ftbtest
      uses: actions/checkout@v2
      with:
        ref: env/ftbtest
    - name: delete tag and release
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        delete_release: true
        tag_name: ftbtest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}







