name: auto deploy release

on:
  push:
    branch:
      - 'main'


jobs:
 create-new-release:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout ftbtest
      uses: actions/checkout@v2
      with:
        ref: env/ftbtest
    - name: delete tag and release
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        delete_release: true
        tag_name: ftbtest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      id: create_release
      uses:  actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ftbtest
        release_name: ftbtest
        commitish: env/ftbtest
        body: |
          Changes in this Release
          - manifest on push tag
        draft: false
        prerelease: false